name: easy_travel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  flutter_bloc: ^9.1.1
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
